config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"
  get "help" => "static_pages#help"
  get "contact" => "static_pages#contact"
  get "about" => "static_pages#about"
  
  get "signup" => "users#new"
  get "login" => "sessions#new"
  post "login" => "sessions#create"
  delete "logout" => "sessions#destroy"

  resources :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  before_save :email_downcase

  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
    format: { with: VALID_EMAIL_REGEX },
    uniqueness: { case_sensitive: false }
  validates :gender, inclusion: { in: ["Male", "Female"] }
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true
  
  has_secure_password

  private
    def email_downcase
      self.email = self.email.downcase
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :user_not_logged_in, only: [:new, :create]

  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && !!user.authenticate(params[:session][:password])
      log_in user
      flash[:success] = "Login successfully"
      redirect_to user
    else
      flash[:danger] = "Invalid email/password combination"
      render "new"
    end
  end

  def destroy
    log_out if logged_in?
    redirect_to root_path
  end

  private
    def user_not_logged_in
      if logged_in?
        redirect_to user_path current_user
        flash[:warning] = "Plz log out before login"
      end
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end

  def contact
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find params[:id]
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new user_params
    if @user.save
      redirect_to @user
      flash[:success] = "Welcome to Sample App"
    else
      render "new"
    end
  end

  private
    def user_params
      params.require(:user).permit(:name, :email, :password,
        :password_confirmation, :gender)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title page_title
    base_title = "Ruby on Rails Sample App"
    if page_title.empty?
      base_title
    else
      page_title + " | " + base_title
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in user
    session[:user_id] = user.id
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !current_user.nil?
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for(user, option = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = option[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/layouts/_footer.html.haml
%footer.footer
  %small
    The
    %a{ href: "http://www.railstutorial.org" } Ruby on Rails Tutorail
    by
    %a{ href: "http://www.michealhartl.com" } Micheal Hartl
  %nav
    %ul
      %li
        = link_to "About", about_path
      %li
        = link_to "Contact", contact_path
      %li
        = link_to "News", "http://news.railstutorial.org"

app/views/layouts/_header.html.haml
%header.navbar.navbar-fixed-top.navbar-inverse
  .container
    = link_to "sample app", root_path, id: "logo"
    %nav
      %ul.nav.navbar-nav.navbar-right
        %li
          = link_to "Home", root_path
        %li
          = link_to "Help", help_path
        - if logged_in?
          %li
            = link_to "Users", "#"
          %li.dropdown
            %a.dropdown-toggle{ href: "#", "data-toggle" => "dropdown" } 
              Account
              %span.caret
            %ul.dropdown-menu
              %li
                = link_to "Profile", current_user
              %li= link_to "Setting", "#"
              %li.divider
                %li
                  = link_to "Log out", logout_path, method: :delete
        - else
          %li= link_to "Log in", login_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title 
      = full_title(yield(:title))
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = render "layouts/header"
    .container
      #flash
        - flash.each do |type, message|
          %div{ class: "alert alert-#{ type }" }
            = message
      = yield
      = render "layouts/footer"

:javascript
  $(document).ready(function(){
    setTimeout(function(){
      $("#flash").remove();
    }, 5000);
  })

app/views/shared/_error_messages.html.haml
- if object.errors.any?
  #error_explanation
    .alert.alert-danger
      The form contains #{pluralize(object.errors.count, "error")}.
    %ul
      - object.errors.full_messages.each do |message|
        %li
          = message

app/views/static_pages/about.html.haml
- provide(:title, "About")
%h1 About
%p 
  The
  %a{ href: "http://railstutorial.org" }
    %em Ruby on Rails Tutorial
  is a
  %a{ href: "http://railstutorial.org/book" } book
  and
  %a{ href: "http://screencasts.railstutorial.org" } screen cast series
  to teach web development with
  %a{ href: "http://rubyonrails.org" } Ruby on Rails.

app/views/static_pages/contact.html.haml
- provide(:title, "Contact")
%h1 Contact
%p 
  Contact the Ruby on Rails Tutorail about the sample app at the
  %a{ href: "http://www.railstutorial.org/contact" } contact page.

app/views/static_pages/help.html.haml
- provide(:title, "Help")
%h1 Help
%p
  Get help on the Ruby on Rails Tutorial at the
  %a{ href: "http://www.railstutorial.org/help" }Rails Tutorial help page.
  To get help on this sample app, see the
  %a{ href: "http://www.railstutorial.org/book" }
    %em Ruby on Rails Tutorial
    book.

app/views/static_pages/home.html.haml
.center.jumbotron
  %h1 Welcome to Sample App
  %h2
    This is the home page for the
    %a{ href: "http://railstutorial.org" } Ruby on Rails Tutorial
    sample application.
  = link_to "Sign up now!", signup_path, class: "btn btn-lg btn-primary"
= link_to image_tag("rails.png", alt: "Rails logo"), 
  "http://railstutorial.org"

app/views/users/new.html.haml
- provide(:title, "Signup")
%h1 Sign Up
.row
  .col-md-6.col-md-offset-3
    = form_for @user do |f|
      = render "shared/error_messages", object: f.object

      %label Name
      = f.text_field :name, class: "form-control"

      %label Email
      = f.email_field :email, class: "form-control"

      %label Password
      = f.password_field :password, class: "form-control"

      %label Confirmation
      = f.password_field :password_confirmation, class: "form-control"

      %label.col-md-3{ style: "text-align: left;" } Gender
      .col-md-9
        .col-md-6{ style: "text-align: center;" }
          %label Male
          = f.radio_button :gender, "Male", checked: true
        .col-md-6{ style: "text-align: center;" }
          %label Female
          = f.radio_button :gender, "Female"
      = f.submit "Create new account", class: "btn btn-primary", style: "margin-top: 10px;"

app/views/users/show.html.haml
- provide(:title, @user.name)
.row
  %aside.col-md-4
    %section.user_info
      %h1
        = gravatar_for @user
        = @user.name